[project]
name = "sourcecrafthackathon"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.30.0",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "scipy>=1.18.1",
    "sqlalchemy>=2.0.54",
    "psycopg2-binary>=2.9.13",
    "apscheduler>=3.11.3",
]
